### ISSUE TITLE
No funciona

### ISSUE THREAD

**Issue by MzHyde98** [aleshyy/docer-libre#1]
Holaa, no se si tengo que poner esto aca pero bueno, no me funciona la extensión, sigo los paso pero no descarga nada ademas de que en la pagina no me aparece el captcha cuando pongo descargar, no se si tiene algo que ver pero no se que hacer porque quiero descargar el pdf pero no puedo y no hay ningún programa o página además de tu extensión para hacerlo, por favor ayudamee

**Comment by aleshyy** [comment]
Hola, ¿cómo estás? Lamento que no puedas descargar el documento que necesitás. La extensión funciona correctamente, a lo mejor, hay algo que estás haciendo mal. Te dejo el siguiente enlace con un "tutorial" de como podés descargarte cualquier documento: https://streamable.com/gimsf9

Avisame si te funcionó, saludos

**Comment by MzHyde98** [comment]
No puedoooo, no se que hago mal, hago lo mismo del video pero no descarga, no se si descargo mal los archivos o que, pongo el link que dice ahi en las instrucciones y descargo el primer archivo de los 3 que están y hago bien los pasos para agregarlo a chrome pero cuando lo quiero usar no puedo, el pdf pesa 2.5MB no si sea eso.
Acabo de probar con otros archivos, y parece que es por el peso del archivo, los archivos que pesan 1.0MB para arriba no los puedo descargar, pero si pesan en KB puedo descargar cualquiera, no se porque sera

**Comment by aleshyy** [comment]
Hola, ¿estás seguro que estás en docer.com.ar, y siguiendo los pasos que te indiqué? Es raro que no te deje, justamente la extensión permite descargar archivos de 1mb o más, esa es la idea. 
Estoy trabajando en una actualización que a lo mejor, soluciona el error que te ocurre. Pronto estará disponible.

**Comment by MzHyde98** [comment]
Hola, creo que encontre el problema, la página en la que estaba era docer.ar, no docer.com.ar, no se porque creo que son diferentes, en la de docer.com.ar no esta el pdf que quiero descargar pero si está en la otra página (docer.ar) asique no se capaz tendrías que habilitar la otra página o lo que sea, no se como funciona eso, así que gracias igual vere si consigo el pdf desde otra pag o si espero la actualizacion de tu extensión

**Comment by mickyelmouse** [comment]
Hola, yo hace un rato tuve el mismo problema con la extension, la pagina me redirigia a otra llamada docer.ar y creo que por eso no funcionaba. Luego de volver al inicio de docer.com.ar inicie sesion con una cuenta de google y recien ahi cuando busque el documento se mantuvo en el dominio docer.com.ar y la extension anduvo. Fijate si te pasa lo mismo a lo mejor era eso.

**Comment by frankyARG** [comment]
Lo informado por [mickyelmouse] es correcto.
